# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  ports:
    - name: metrics
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
